name: Windows Build

on: 
  workflow_dispatch:

jobs:
  BuildWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir Build
      - run: cd Build
      - run: cmake .. -G"Visual Studio 14 2015"
      - run: msbuild
      - run: cd ..
      - uses: actions/upload-artifact@v2
        with:
          name: WindowsBuild
          path: Build/*

